Module 2 homework
ArtsiomMusin/thinknetica_react pull request #2
Opened 2017-10-28 11:17 UTC by ArtsiomMusin

2017-10-29 05:35 UTC, index01d requested changes
Не нашел кнопки Like из задания

2017-10-29 05:35 UTC, index01d commented on blog_item.js
>  const three_items = [
лучше придерживаться camelCase'a в именованиях (threeItems)

2017-10-29 05:35 UTC, index01d commented on blog_item.js
>  const list = _.map(three_items, (item, index) =>
Компоненты именуются с большой буквы и должны представлять собою функцию `() => ...`, в данном случае list получился просто статическим набором элементов и для него не будут выполняться шаги жизненного цикла компонента.

2017-10-29 05:35 UTC, index01d commented on blog_item.js
> +      React.createElement(TextBox, {text: this.props.text}),
лучше передавать текст третьим аргументом функции createElement и принимать его в children свойстве компонента TextBox

2017-10-29 05:35 UTC, index01d commented on blog_item.js
> +  render() {
здесь в первой строчке можно предварительно деструктурировать нужные параметры из this.props
`const { src, text, created, updated, author } = this.props;`

тогда на месте можно будет использовать более короткую запись
`React.createElement(Image, { src })`

2017-10-29 05:35 UTC, index01d commented on blog_item.js
>      src: "https://goo.gl/J4q89x",
для картинки можно выделить отдельный объект: 
```
{
  ...
  image: { src: '...' }
  ...
}
```

Для meta еще один:
```
{
   ...
   image: { src: ... }
   meta: { created: ..., updated: ..., author: ... }
}
```

Если этого не делать, то свойства для разных элементов перемешаются в списке.

К тому же стоит избавиться от дублирования аргумента формата в moment и сделать высокоуровневую функцию formatDate(date), в которой использовать moment. Во-первых так проще будет поменять формат даты по всему коду, во-вторых так проще будет заменить moment на другую библиотеку работы с датой, в случае необходимости.

2017-10-29 05:35 UTC, index01d commented on blog_list.js
> +                src: item.src,
можно просто передать item вместо объекта со свойствами. Списку не рекомендуется знать о наборе свойств, иначе в случае изменения этого набора потребуется править и список и BlogItem

2017-10-29 05:35 UTC, index01d commented on blog_list.js
> +  list: PropTypes.array
лучше везде называть свойства одинаково (items, item), чем меньше названий, тем проще сопоставлять объекты

2017-10-29 12:08 UTC, ArtsiomMusin commented
Не нашел кнопки Like?... вроде все на месте в blog_item.js:30. Плюс в описание PR добавил ссылка на jsbin demo.

2017-10-29 13:42 UTC, ArtsiomMusin commented on blog_item.js
> +  render() {
ok, исправил

2017-10-29 13:42 UTC, ArtsiomMusin commented on blog_item.js
> +      React.createElement(TextBox, {text: this.props.text}),
вроде поменял на то, что надо, если я все правильно понял... :slightly_smiling_face:

2017-10-29 13:42 UTC, ArtsiomMusin commented on blog_item.js
>  const three_items = [
Исправил(руби привычка :) )

2017-10-29 13:43 UTC, ArtsiomMusin commented on blog_item.js
>      src: "https://goo.gl/J4q89x",
ok.
1. Выделил отдельные объекты для картинки и meta.
2. Вынес обработку времени в отдельную функцию

2017-10-29 13:43 UTC, ArtsiomMusin commented on blog_item.js
>  const list = _.map(three_items, (item, index) =>
Ну я и не думал делать list компонентой... хотел, чтобы был просто список, который используеться только для рендеринга трех независимых BlogItem'ов. Вроде в первом задании для первого модуля не надо было делать компоненту List, а просто отрендерить BlogItem'ы.

или переделать?

2017-10-29 13:43 UTC, ArtsiomMusin commented on blog_list.js
> +                src: item.src,
Этот коммент получается не совсем актуальным, так как я разбил свойства на две части. В первой части только image(со свойством src) и вторая часть - meta. 
Теперь выглядит так:
``BlogItem, 
      {
        image: item.image,
        text: item.text,        
        meta: item.meta      
      }
``
Или все равно лучше просто item передавать?

2017-10-29 13:43 UTC, ArtsiomMusin commented on blog_list.js
> +  list: PropTypes.array
ok, поменял list на items

2017-10-30 05:03 UTC, blackleadsu requested changes
Немного пояснил то, что имел ввиду Эдуард.

2017-10-30 05:03 UTC, blackleaden commented on blog_item.js
> +      DOM.div(
Следует вынести отдельным компонентом (по заданию).

2017-10-30 05:03 UTC, blackleaden commented on blog_item.js
> +const list = _.map(threeItems, (item, index) =>
На будущее: лучше не использовать в качестве ключа индекс в списке, лучше завести отдельный id записи. Ключи нужны реакту чтобы различать разные элементы динамического списка. Так, в будущем (например при перелистывании страницы или при поиске) передаваемый набор записей будет меняться, а индексы -- нет. Разные по содержимому элементы требуют разных ключей. Если изменилось содержимое отдельного элемента ключ менять, конечно, не нужно.
Подробнее в доках: https://reactjs.org/docs/lists-and-keys.html#keys

2017-10-30 06:42 UTC, ArtsiomMusin commented on blog_item.js
> +      DOM.div(
оу, точно! :smile:  С раза пятого только заметил это в задании... смотришь в книгу, видишь фигу :man_facepalming: 
Добавил.

2017-10-30 08:19 UTC, blackleadsu approved these changes

2017-10-31 07:01 UTC, merged