Module 3 homework
ArtsiomMusin/thinknetica_react pull request #3
Opened 2017-11-01 08:12 UTC by ArtsiomMusin

Demo: http://jsbin.com/cemaharoyu/edit?html,js,output

2017-11-02 22:01 UTC, index01d requested changes

2017-11-02 22:01 UTC, index01d commented on blog_list.js
> +                like: () => this.state.like(item.id)
пробрасывать в состояние свойства это здесь лишнее. нужно напрямую оперировать свойствами

2017-11-02 22:01 UTC, index01d commented on blog_page.js
> +    if(!obj.meta.likes_count){
лучше использовать в названии camelCase: `likesCount`

2017-11-02 22:01 UTC, index01d commented on blog_page.js
> +    obj.meta.likes_count += 1; // wtf I wrote here?
здесь ты меняешь значение напрямую в состоянии (состояние является мутабельным) без использования функции setState, что противоречит правилам работы с состоянием, используй `update` из https://github.com/kolodny/immutability-helper или делай копию состояния

2017-11-03 06:51 UTC, ArtsiomMusin commented on blog_list.js
> +                like: () => this.state.like(item.id)
понятно, в начале я и думал просто все свойства пробрасывать, но подумал, что это будет немного криво

2017-11-03 06:51 UTC, ArtsiomMusin commented on blog_page.js
> +    if(!obj.meta.likes_count){
изменил

2017-11-03 06:51 UTC, ArtsiomMusin commented on blog_page.js
> +    obj.meta.likes_count += 1; // wtf I wrote here?
я это осознал после прочтения одной статьи и это было через день после того как я PR отправил :slightly_smiling_face: Исправил

2017-11-04 06:47 UTC, index01d requested changes

2017-11-04 06:47 UTC, index01d commented on blog_list.js
> +                like: this.state.like,
this.props.items и this.props.like; зачем здесь использовать состояние?

2017-11-04 08:20 UTC, ArtsiomMusin commented on blog_list.js
> +                like: this.state.like,
угу, тут оно и не надо, убрал из конструктора тоже

2017-11-05 10:18 UTC, merged