Module 6 homework
ArtsiomMusin/thinknetica_react pull request #6
Opened 2017-11-15 22:53 UTC by ArtsiomMusin

2017-11-17 08:48 UTC, index01d requested changes

2017-11-17 08:48 UTC, index01d commented on src/App.js
> +function historyCb(location) {
отступ бы:)

2017-11-17 08:48 UTC, index01d commented on src/actions/Posts.js
> +const increaseLikes = (id) => ({
лучше выделить в отдельный модуль `actions/Like`

2017-11-17 08:48 UTC, index01d commented on src/actions/Posts.js
> +      .get('http://localhost:3001')
лучше вынести хост в константу

2017-11-17 08:48 UTC, index01d commented on src/actions/Posts.js
> +      .get('http://localhost:3001')
в отдельный модуль `constants/API`

2017-11-17 08:48 UTC, index01d commented on src/components/containers/BlogPage.js
>  class BlogPage extends React.Component {
Имеет смысл сделать этот компонент stateless и выделить отдельно PieChartContainer

2017-11-17 08:48 UTC, index01d commented on src/components/ui/BlogList.js
> +  let list =  _.map(
должно быть в контейнере

2017-11-17 08:48 UTC, index01d commented on src/components/ui/BlogList.js
> +  like: PropTypes.func,
лучше реализовать LikeContainer и не носить функцию по иерархии

2017-11-17 08:48 UTC, index01d commented on src/containers/PostsContainer.js
> +    items: state.posts.entries,
выборку нужного числа постов лучше сделать здесь

2017-11-17 08:48 UTC, index01d commented on src/containers/PostsContainer.js
> +    like: (id) => {
лучше выделить в LikeContainer

2017-11-17 20:45 UTC, ArtsiomMusin commented on src/actions/Posts.js
> +const increaseLikes = (id) => ({
вначале сделал отдельно, но потом включил как часть Posts. Переделал на отдельный модуль.

2017-11-17 20:45 UTC, ArtsiomMusin commented on src/actions/Posts.js
> +      .get('http://localhost:3001')
точно, забыл вынести в константу

2017-11-17 20:45 UTC, ArtsiomMusin commented on src/components/containers/BlogPage.js
>  class BlogPage extends React.Component {
Исправил

2017-11-17 20:46 UTC, ArtsiomMusin commented on src/components/ui/BlogList.js
> +  let list =  _.map(
частично перенес, надеюсь этого хватит? или надо прям все выносить?

2017-11-17 20:46 UTC, ArtsiomMusin commented on src/components/ui/BlogList.js
> +  like: PropTypes.func,
ох да! так в коде гораздо лучше стало! :+1:

2017-11-17 20:46 UTC, ArtsiomMusin commented on src/containers/PostsContainer.js
> +    items: state.posts.entries,
сделал, но только в BlogList'e

2017-11-17 20:46 UTC, ArtsiomMusin commented on src/containers/PostsContainer.js
> +    like: (id) => {
ok, исправил

2017-11-20 15:35 UTC, index01d approved these changes
Понято верно, но есть замечания

2017-11-20 15:35 UTC, index01d commented on src/containers/LikeContainer.js
> +const mapDispatchToProps = (dispatch) => (
в эту функцию вторым аргументом приходит объект ownProps, из него можно взять id

2017-11-20 15:35 UTC, index01d commented on src/containers/LikeContainer.js
> +    like: (id) => {
тогда здесь id не нужен

2017-11-20 15:35 UTC, index01d commented on src/containers/PostsSearchContainer.js
> +    search: (id) => {
здесь также можно брать id из ownProps

2017-11-20 15:35 UTC, index01d commented on src/components/containers/BlogPage.js
> +        <PostsSearchContainer />
здесь можно сразу передать id, если нужно

2017-11-20 15:35 UTC, index01d commented on src/components/ui/BlogItem.js
> +                  <LikeContainer count={meta.likesCount} id={id} />
здесь уже передается id

2017-11-20 19:41 UTC, ArtsiomMusin commented on src/components/containers/BlogPage.js
> +        <PostsSearchContainer />
криво код написал... там вместо id должен был быть event, а его здесь никак не передашь

2017-11-20 19:41 UTC, ArtsiomMusin commented on src/containers/LikeContainer.js
> +    like: (id) => {
:+1: Исправил

2017-11-20 19:41 UTC, ArtsiomMusin commented on src/containers/PostsSearchContainer.js
> +    search: (id) => {
тоже самое что и в первом комменте.

2017-11-22 20:17 UTC, merged