Module 7 homework
ArtsiomMusin/thinknetica_react pull request #7
Opened 2017-11-24 13:10 UTC by ArtsiomMusin

2017-11-25 06:43 UTC, index01d requested changes

2017-11-25 06:43 UTC, index01d commented on src/containers/LikeContainer.js
> +    activePage: state.pagination.activePage
Зачем лайку знать про пейджинацию?

2017-11-25 06:43 UTC, index01d commented on src/containers/LikeContainer.js
> +      dispatchProps.updatePosts(stateProps.activePage);
зачем лайку знать про updatePosts? почему не обработать like в reducer'e?

2017-11-25 06:43 UTC, index01d commented on src/reducers/Posts.js
> +  if (_.isEmpty(state.entries)) {
лучше импортировать конкретные функции из lodash `import { isEmpty } from 'lodash'`, тогда в итоговый bundle попадет не вся библиотека (при использовании tree-shaking), а запись будет короче

2017-11-25 06:43 UTC, index01d commented on blogServer/index.js
> +  var itemToReturn = items;
надо тут все декомпозировать, именовать и всячески рефачить.

2017-11-25 12:31 UTC, ArtsiomMusin commented on blogServer/index.js
> +  var itemToReturn = items;
Исправил

2017-11-25 12:31 UTC, ArtsiomMusin commented on src/containers/LikeContainer.js
> +    activePage: state.pagination.activePage
чота я перемудрил с лайками :sweat_smile: Я увеличение счетчика лайков делал в бэкэнде, а потом просто получал еще раз все посты и текущую старницу пэйджинации.

Подправил код, вынес логику в редюсер

2017-11-25 12:31 UTC, ArtsiomMusin commented on src/reducers/Posts.js
> +  if (_.isEmpty(state.entries)) {
подправил

2017-11-26 17:11 UTC, index01d approved these changes

2017-11-26 18:58 UTC, merged